### ISSUE TITLE
As a user I want to delete files and see the deleted files

### ISSUE THREAD

**Issue by mina-sebastian** [mina-sebastian/free-space#52]
## Frontend
- **UI for Deleting Files**: Design and implement a user interface component that allows users to select and delete files. Include confirmation dialogs to prevent accidental deletions.
- **Deleted Files View**: Create a separate interface or section where users can view their recently deleted files, with options to restore or permanently remove them.
- **Feedback and Error Handling in the UI**: Implement user feedback for deletion actions, including success notifications and error messages if a deletion fails.

## Backend
- **API Endpoint for Deleting Files**: Develop an API endpoint that handles file deletion requests, ensuring secure authentication and authorization checks.
- **API Endpoint for Retrieving Deleted Files**: Create an API endpoint that provides a list of deleted files for a user.
- **Logic for Managing Deleted Files**: Implement backend logic to manage the lifecycle of deleted files, including permanent deletion after a certain period or when requested by the user.

**Comment by Yanis3Pique** [comment]
git fetch origin
git checkout 52-as-a-user-i-want-to-delete-files-and-see-the-deleted-files
