### ISSUE TITLE
As a user I want to see the storage consumed and available free space

### ISSUE THREAD

**Issue by mina-sebastian** [mina-sebastian/free-space#53]
## Frontend
- **Storage Usage Dashboard**: Design and implement a dashboard or widget in the user interface that displays the current storage usage. This should include visual representations (like a progress bar or pie chart) showing the percentage of storage used and the remaining free space.
- **Real-Time Storage Updates**: Ensure the storage usage display updates in real-time or near real-time as files are added or deleted.
- **User Interface Feedback**: Provide tooltips or help icons explaining what the storage metrics mean, and possibly suggest actions if the storage limit is nearing capacity.

## Backend
- **API Endpoint for Storage Data**: Develop an API endpoint that retrieves detailed storage usage data for a user, including total capacity, space used, and available free space.
- **Storage Calculation Logic**: Implement logic to calculate current storage usage and remaining space, factoring in file additions and deletions.

**Comment by Victor2626** [comment]
git fetch origin
git checkout 53-as-a-user-i-want-to-see-the-storage-consumed-and-available-free-space
